name: Build FreeType Multi-Platform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Configure CMake
        run: |
          cd freetype
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -D BUILD_SHARED_LIBS=ON

      - name: Build FreeType DLL
        run: cmake --build freetype/build --config Release

      - name: Upload DLL as artifact
        uses: actions/upload-artifact@v4
        with:
          name: freetype-windows-dll
          path: freetype/build/Release/freetype.dll

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Configure CMake
        run: |
          cd freetype
          mkdir build
          cd build
          cmake .. -D BUILD_SHARED_LIBS=ON

      - name: Build FreeType dynamic library
        run: cmake --build freetype/build --config Release

      - name: Upload dylib as artifact
        uses: actions/upload-artifact@v4
        with:
          name: freetype-macos-dylib
          path: freetype/build/libfreetype.dylib

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: |
          cd freetype
          mkdir build
          cd build
          cmake .. -D BUILD_SHARED_LIBS=ON

      - name: Build FreeType shared object
        run: cmake --build freetype/build --config Release

      - name: Upload so as artifact
        uses: actions/upload-artifact@v4
        with:
          name: freetype-linux-so
          path: freetype/build/libfreetype.so

  create-release:
    name: Create GitHub Release
    needs: [build-windows, build-macos, build-linux] # 依赖于所有构建 Job
    if: success()
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予创建 Release 所需的写权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true' # 确保拉取子模块，以便读取 README.md

      - name: Get FreeType Version from submodule README
        id: get_version # 为这个步骤设置 ID，以便后续步骤访问其输出
        run: |
          # 从本地已检出的子模块中读取版本号
          VERSION=$(head -n 1 freetype/README | grep -oE '([0-9]+\.[0-9]+\.[0-9]+)')
          echo "FreeType Version: $VERSION"
          # 将版本号设置为 Job 的输出，以便在 with: 中使用
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Download FreeType License Files
        run: |
          mkdir -p ./licenses
          cp freetype/LICENSE.TXT ./licenses/
          cp freetype/docs/FTL.TXT ./licenses/
          cp freetype/docs/GPLv2.TXT ./licenses/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          # 现在从 get_version 步骤的输出中获取版本号
          tag_name: freetype-v${{ steps.get_version.outputs.version }}
          name: FreeType v${{ steps.get_version.outputs.version }} Binaries
          body: |
            This release contains pre-built FreeType binaries for Windows, macOS, and Linux.
            
            Based on FreeType version: ${{ steps.get_version.outputs.version }}
            
            **Included files:**
            - Windows DLL: `freetype.dll`
            - macOS Dynamic Library: `libfreetype.dylib`
            - Linux Shared Object: `libfreetype.so`
            - **License files**
          files: |
            ./artifacts/freetype-windows-dll/freetype.dll
            ./artifacts/freetype-macos-dylib/libfreetype.dylib
            ./artifacts/freetype-linux-so/libfreetype.so
            ./licenses/LICENSE.TXT
            ./licenses/FTL.TXT
            ./licenses/GPLv2.TXT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}