name: Build FreeType Multi-Platform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Configure CMake
        run: |
          cd freetype
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -D BUILD_SHARED_LIBS=ON

      - name: Build FreeType DLL
        run: cmake --build freetype/build --config Release

      - name: Upload DLL as artifact
        uses: actions/upload-artifact@v4
        with:
          name: freetype-windows-dll
          path: freetype/build/Release/freetype.dll

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Configure CMake
        run: |
          cd freetype
          mkdir build
          cd build
          cmake .. -D BUILD_SHARED_LIBS=ON

      - name: Build FreeType dynamic library
        run: cmake --build freetype/build --config Release

      - name: Upload dylib as artifact
        uses: actions/upload-artifact@v4
        with:
          name: freetype-macos-dylib
          path: freetype/build/libfreetype.dylib

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: |
          cd freetype
          mkdir build
          cd build
          cmake .. -D BUILD_SHARED_LIBS=ON

      - name: Build FreeType shared object
        run: cmake --build freetype/build --config Release

      - name: Upload so as artifact
        uses: actions/upload-artifact@v4
        with:
          name: freetype-linux-so
          path: freetype/build/libfreetype.so

  create-release:
    name: Create GitHub Release
    needs: [build-windows, build-macos, build-linux]
    if: success()
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予创建 Release 所需的写权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      # 新增步骤：下载 FreeType 许可文档
      - name: Download FreeType License Files
        run: |
          mkdir -p ./licenses
          # 这里我们从本地子模块中复制许可文档
          cp freetype/LICENSE.TXT ./licenses/
          cp freetype/docs/FTL.TXT ./licenses/
          cp freetype/docs/GPLv2.TXT ./licenses/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: freetype-v${{ needs.check-for-update.outputs.new_version }}
          name: FreeType v${{ needs.check-for-update.outputs.new_version }} Binaries
          body: |
            This release contains pre-built FreeType binaries for Windows, macOS, and Linux.
            
            Based on FreeType version: ${{ needs.check-for-update.outputs.new_version }}
            
            **Included files:**
            - Windows DLL: `freetype.dll`
            - macOS Dynamic Library: `libfreetype.dylib`
            - Linux Shared Object: `libfreetype.so`
            - **License files**
          files: |
            ./artifacts/freetype-windows-dll/freetype.dll
            ./artifacts/freetype-macos-dylib/libfreetype.dylib
            ./artifacts/freetype-linux-so/libfreetype.so
            ./licenses/LICENSE.TXT
            ./licenses/FTL.TXT
            ./licenses/GPLv2.TXT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}