name: Build FreeType Multi-Platform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Configure CMake
        run: |
          cd freetype
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -D BUILD_SHARED_LIBS=ON

      - name: Build FreeType DLL
        run: cmake --build freetype/build --config Release

      - name: Upload DLL as artifact
        uses: actions/upload-artifact@v4
        with:
          name: freetype-windows-dll
          path: freetype/build/Release/freetype.dll

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Configure CMake
        run: |
          cd freetype
          mkdir build
          cd build
          cmake .. -D BUILD_SHARED_LIBS=ON

      - name: Build FreeType dynamic library
        run: cmake --build freetype/build --config Release

      - name: Upload dylib as artifact
        uses: actions/upload-artifact@v4
        with:
          name: freetype-macos-dylib
          path: freetype/build/libfreetype.dylib

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: |
          cd freetype
          mkdir build
          cd build
          cmake .. -D BUILD_SHARED_LIBS=ON

      - name: Build FreeType shared object
        run: cmake --build freetype/build --config Release

      - name: Upload so as artifact
        uses: actions/upload-artifact@v4
        with:
          name: freetype-linux-so
          path: freetype/build/libfreetype.so

  create-release:
    name: Create GitHub Release
    needs: [build-windows, build-macos, build-linux]
    if: success()
    runs-on: ubuntu-latest
    steps:
      # 以下步骤用于获取新版本号
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Get FreeType Version from submodule README
        id: get_version
        run: |
          VERSION=$(head -n 1 freetype/README | grep -oE '([0-9]+\.[0-9]+\.[0-9]+)')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: freetype-windows-dll
          path: ./artifacts/windows

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: freetype-macos-dylib
          path: ./artifacts/macos

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: freetype-linux-so
          path: ./artifacts/linux

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: freetype-v${{ env.VERSION }}
          name: FreeType v${{ env.VERSION }} Binaries
          body: |
            This release contains pre-built FreeType binaries for Windows, macOS, and Linux.
            
            Based on FreeType version: ${{ env.VERSION }}
            
            **Included files:**
            - Windows DLL: `freetype.dll`
            - macOS Dynamic Library: `libfreetype.dylib`
            - Linux Shared Object: `libfreetype.so`
          files: |
            ./artifacts/windows/freetype.dll
            ./artifacts/macos/libfreetype.dylib
            ./artifacts/linux/libfreetype.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}